input.onButtonPressed(Button.A, function () {
    basic.showString("H")
    basic.showString("e")
    basic.showString("l")
    basic.showString("l")
    basic.showString("o")
    basic.pause(1000)
    basic.showString("a")
    basic.showString("n")
    basic.showString("d")
    basic.pause(1000)
    basic.showString("g")
    basic.showString("o")
    basic.showString("o")
    basic.showString("d")
    basic.pause(1000)
    basic.showString("e")
    basic.showString("v")
    basic.showString("e")
    basic.showString("n")
    basic.showString("i")
    basic.showString("n")
    basic.showString("g")
    basic.pause(1000)
    basic.showString("t")
    basic.showString("o")
    basic.pause(1000)
    basic.showString("t")
    basic.showString("h")
    basic.showString("e")
    basic.pause(1000)
    basic.showString("w")
    basic.showString("h")
    basic.showString("o")
    basic.showString("l")
    basic.showString("e")
    basic.pause(1000)
    basic.showString("c")
    basic.showString("l")
    basic.showString("a")
    basic.showString("s")
    basic.showString("s")
    basic.pause(5000)
    basic.showLeds(`
        . # . # .
        # # # # #
        # # # # #
        . # # # .
        . . # . .
        `)
    music.playMelody("E B C5 A B G A F ", 120)
    music.playMelody("E B C5 A B G A F ", 120)
    music.playMelody("E B C5 A B G A F ", 120)
    music.playMelody("E - - - - - - - ", 120)
})
basic.forever(function () {
	
})
